{{- if (and .Values.serviceAccount.create .Values.serviceAccount.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logstash-exporter.serviceAccountName" . }}
  labels:
    app: {{ template "logstash-exporter.name" . }}
    release: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end -}}
